export const header_icons = [{src:"/assets/chatbot_icon.svg",alt:"chatbot"},{src:"/assets/menu_icon.svg" ,alt:"menu_icon"},{src:"/assets/notification_icon.svg", alt:"notification"},{src:"/assets/my_account_dropdown.svg", alt:"my_account_dropdown"}]

export const sidebar_items = [{path:"/1",src:"/assets/Menu1.svg",key:"Menu1",name:"Menu One"},{path:"/2",src:"/assets/Menu2.svg",key:"Menu2",name:"Menu Two"},{path:"/3",src:"/assets/Menu3.svg",key:"Menu3",name:"Menu Three"},{path:"/4",src:"/assets/Menu4.svg",key:"Menu4",name:"Menu Four"},{path:"/5",src:"/assets/Menu5.svg",key:"Menu5",name:"Menu Five"},{path:"/projectMembers",src:"/assets/Menu6.svg",key:"Menu6",name:"Menu Six"},{path:"/7",src:"/assets/Menu7.svg",key:"Menu7",name:"Menu Seven"},{path:"/8",src:"/assets/Menu8.svg",key:"Menu8",name:"Menu Eight"},{path:"/9",src:"/assets/Menu9.svg",key:"Menu9",name:"Menu Nine"},{path:"/10",src:"/assets/Menu10.svg",key:"Menu10",name:"Menu Ten"}]


export const project_members = [{name:"Victor",designation:"Ui Ux Team Lead",img:"/assets/victor.svg"},{name:"Alexa",designation:"Sr. Ui Ux Designer",img:"/assets/alexa.svg"},{name:"Juliet",designation:"Blockchain Dev. Team Lead",img:"/assets/Juliet.svg"},{name:"Hina",designation:"QA Team Lead",img:"/assets/Hina.svg"},{name:"Steve",designation:"Ui Ux Team Manager",img:"/assets/Steve.svg"},{name:"Andrielle",designation:"Sr. Ui Ux Designer",img:"/assets/Andrielle.svg"},{name:"Billie",designation:"Blockchain Dev. Team Manager",img:"/assets/Billie.svg"},{name:"Alita",designation:"QA Team Manager",img:"/assets/Alita.svg"},{name:"Victor",designation:"Ui Ux Team Lead",img:"/assets/victor.svg"},{name:"Alexa",designation:"Sr. Ui Ux Designer",img:"/assets/alexa.svg"},{name:"Juliet",designation:"Blockchain Dev. Team Lead",img:"/assets/Juliet.svg"},{name:"Hina",designation:"QA Team Lead",img:"/assets/Hina.svg"},{name:"Steve",designation:"Ui Ux Team Manager",img:"/assets/Steve.svg"},{name:"Andrielle",designation:"Sr. Ui Ux Designer",img:"/assets/Andrielle.svg"},{name:"Billie",designation:"Blockchain Dev. Team Manager",img:"/assets/Billie.svg"},{name:"Alita",designation:"QA Team Manager",img:"/assets/Alita.svg"}]

export const current_and_upcoming = [{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"}]

export const completed = [{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"}]

export const Failed = [{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"Low"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"},{eventName:"ZEN Roadmap, Boards backlog & Test Hub",ticketNo:"ZEN-01",priority:"High"}]

export const taskStatus = [{percent_completed:"55%",taskName:"Completed Task",taskType:"completed"},{percent_completed:"30%",taskName:"Incompleted Task",taskType:"progress"},{percent_completed:"15%",taskName:"Over due",taskType:"progress"}]